/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactRequest service. Represents a row in the &quot;NXC_ContactRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.nexcent.contact.model.impl.ContactRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.nexcent.contact.model.impl.ContactRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactRequest
 * @generated
 */
@ProviderType
public interface ContactRequestModel
	extends BaseModel<ContactRequest>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact request model instance should use the {@link ContactRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this contact request.
	 *
	 * @return the primary key of this contact request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact request.
	 *
	 * @param primaryKey the primary key of this contact request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this contact request.
	 *
	 * @return the mvcc version of this contact request
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this contact request.
	 *
	 * @param mvccVersion the mvcc version of this contact request
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this contact request.
	 *
	 * @return the uuid of this contact request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contact request.
	 *
	 * @param uuid the uuid of this contact request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the contact request ID of this contact request.
	 *
	 * @return the contact request ID of this contact request
	 */
	public long getContactRequestId();

	/**
	 * Sets the contact request ID of this contact request.
	 *
	 * @param contactRequestId the contact request ID of this contact request
	 */
	public void setContactRequestId(long contactRequestId);

	/**
	 * Returns the group ID of this contact request.
	 *
	 * @return the group ID of this contact request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact request.
	 *
	 * @param groupId the group ID of this contact request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact request.
	 *
	 * @return the company ID of this contact request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact request.
	 *
	 * @param companyId the company ID of this contact request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact request.
	 *
	 * @return the user ID of this contact request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact request.
	 *
	 * @param userId the user ID of this contact request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact request.
	 *
	 * @return the user uuid of this contact request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact request.
	 *
	 * @param userUuid the user uuid of this contact request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact request.
	 *
	 * @return the user name of this contact request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact request.
	 *
	 * @param userName the user name of this contact request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact request.
	 *
	 * @return the create date of this contact request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact request.
	 *
	 * @param createDate the create date of this contact request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact request.
	 *
	 * @return the modified date of this contact request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact request.
	 *
	 * @param modifiedDate the modified date of this contact request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this contact request.
	 *
	 * @return the first name of this contact request
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this contact request.
	 *
	 * @param firstName the first name of this contact request
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this contact request.
	 *
	 * @return the last name of this contact request
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this contact request.
	 *
	 * @param lastName the last name of this contact request
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email address of this contact request.
	 *
	 * @return the email address of this contact request
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this contact request.
	 *
	 * @param emailAddress the email address of this contact request
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the contact details of this contact request.
	 *
	 * @return the contact details of this contact request
	 */
	@AutoEscape
	public String getContactDetails();

	/**
	 * Sets the contact details of this contact request.
	 *
	 * @param contactDetails the contact details of this contact request
	 */
	public void setContactDetails(String contactDetails);

	/**
	 * Returns the status of this contact request.
	 *
	 * @return the status of this contact request
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this contact request.
	 *
	 * @param status the status of this contact request
	 */
	public void setStatus(String status);

	@Override
	public ContactRequest cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:353769626