/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.contact.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.nexcent.contact.model.ContactRequest;
import com.nexcent.contact.model.ContactRequestModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ContactRequest service. Represents a row in the &quot;NXC_ContactRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContactRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactRequestImpl
 * @generated
 */
public class ContactRequestModelImpl
	extends BaseModelImpl<ContactRequest> implements ContactRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact request model instance should use the <code>ContactRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "NXC_ContactRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"contactRequestId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"firstName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"emailAddress", Types.VARCHAR},
		{"contactDetails", Types.VARCHAR}, {"status", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactRequestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactDetails", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NXC_ContactRequest (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,contactRequestId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,emailAddress VARCHAR(75) null,contactDetails VARCHAR(75) null,status VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table NXC_ContactRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contactRequest.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NXC_ContactRequest.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ContactRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contactRequestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContactRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contactRequestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContactRequest.class;
	}

	@Override
	public String getModelClassName() {
		return ContactRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContactRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContactRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContactRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContactRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContactRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContactRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContactRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContactRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ContactRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ContactRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ContactRequest, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ContactRequest::getMvccVersion);
			attributeGetterFunctions.put("uuid", ContactRequest::getUuid);
			attributeGetterFunctions.put(
				"contactRequestId", ContactRequest::getContactRequestId);
			attributeGetterFunctions.put("groupId", ContactRequest::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ContactRequest::getCompanyId);
			attributeGetterFunctions.put("userId", ContactRequest::getUserId);
			attributeGetterFunctions.put(
				"userName", ContactRequest::getUserName);
			attributeGetterFunctions.put(
				"createDate", ContactRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ContactRequest::getModifiedDate);
			attributeGetterFunctions.put(
				"firstName", ContactRequest::getFirstName);
			attributeGetterFunctions.put(
				"lastName", ContactRequest::getLastName);
			attributeGetterFunctions.put(
				"emailAddress", ContactRequest::getEmailAddress);
			attributeGetterFunctions.put(
				"contactDetails", ContactRequest::getContactDetails);
			attributeGetterFunctions.put("status", ContactRequest::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ContactRequest, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ContactRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<ContactRequest, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ContactRequest, Long>)
					ContactRequest::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<ContactRequest, String>)ContactRequest::setUuid);
			attributeSetterBiConsumers.put(
				"contactRequestId",
				(BiConsumer<ContactRequest, Long>)
					ContactRequest::setContactRequestId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ContactRequest, Long>)ContactRequest::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ContactRequest, Long>)ContactRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ContactRequest, Long>)ContactRequest::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ContactRequest, String>)
					ContactRequest::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ContactRequest, Date>)
					ContactRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ContactRequest, Date>)
					ContactRequest::setModifiedDate);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<ContactRequest, String>)
					ContactRequest::setFirstName);
			attributeSetterBiConsumers.put(
				"lastName",
				(BiConsumer<ContactRequest, String>)
					ContactRequest::setLastName);
			attributeSetterBiConsumers.put(
				"emailAddress",
				(BiConsumer<ContactRequest, String>)
					ContactRequest::setEmailAddress);
			attributeSetterBiConsumers.put(
				"contactDetails",
				(BiConsumer<ContactRequest, String>)
					ContactRequest::setContactDetails);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<ContactRequest, String>)ContactRequest::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getContactRequestId() {
		return _contactRequestId;
	}

	@Override
	public void setContactRequestId(long contactRequestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactRequestId = contactRequestId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emailAddress = emailAddress;
	}

	@Override
	public String getContactDetails() {
		if (_contactDetails == null) {
			return "";
		}
		else {
			return _contactDetails;
		}
	}

	@Override
	public void setContactDetails(String contactDetails) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactDetails = contactDetails;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ContactRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ContactRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContactRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContactRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContactRequestImpl contactRequestImpl = new ContactRequestImpl();

		contactRequestImpl.setMvccVersion(getMvccVersion());
		contactRequestImpl.setUuid(getUuid());
		contactRequestImpl.setContactRequestId(getContactRequestId());
		contactRequestImpl.setGroupId(getGroupId());
		contactRequestImpl.setCompanyId(getCompanyId());
		contactRequestImpl.setUserId(getUserId());
		contactRequestImpl.setUserName(getUserName());
		contactRequestImpl.setCreateDate(getCreateDate());
		contactRequestImpl.setModifiedDate(getModifiedDate());
		contactRequestImpl.setFirstName(getFirstName());
		contactRequestImpl.setLastName(getLastName());
		contactRequestImpl.setEmailAddress(getEmailAddress());
		contactRequestImpl.setContactDetails(getContactDetails());
		contactRequestImpl.setStatus(getStatus());

		contactRequestImpl.resetOriginalValues();

		return contactRequestImpl;
	}

	@Override
	public ContactRequest cloneWithOriginalValues() {
		ContactRequestImpl contactRequestImpl = new ContactRequestImpl();

		contactRequestImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		contactRequestImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		contactRequestImpl.setContactRequestId(
			this.<Long>getColumnOriginalValue("contactRequestId"));
		contactRequestImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		contactRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		contactRequestImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		contactRequestImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		contactRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		contactRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		contactRequestImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		contactRequestImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		contactRequestImpl.setEmailAddress(
			this.<String>getColumnOriginalValue("emailAddress"));
		contactRequestImpl.setContactDetails(
			this.<String>getColumnOriginalValue("contactDetails"));
		contactRequestImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));

		return contactRequestImpl;
	}

	@Override
	public int compareTo(ContactRequest contactRequest) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), contactRequest.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ContactRequest)) {
			return false;
		}

		ContactRequest contactRequest = (ContactRequest)object;

		long primaryKey = contactRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactRequest> toCacheModel() {
		ContactRequestCacheModel contactRequestCacheModel =
			new ContactRequestCacheModel();

		contactRequestCacheModel.mvccVersion = getMvccVersion();

		contactRequestCacheModel.uuid = getUuid();

		String uuid = contactRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contactRequestCacheModel.uuid = null;
		}

		contactRequestCacheModel.contactRequestId = getContactRequestId();

		contactRequestCacheModel.groupId = getGroupId();

		contactRequestCacheModel.companyId = getCompanyId();

		contactRequestCacheModel.userId = getUserId();

		contactRequestCacheModel.userName = getUserName();

		String userName = contactRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contactRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contactRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			contactRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contactRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contactRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contactRequestCacheModel.firstName = getFirstName();

		String firstName = contactRequestCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			contactRequestCacheModel.firstName = null;
		}

		contactRequestCacheModel.lastName = getLastName();

		String lastName = contactRequestCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			contactRequestCacheModel.lastName = null;
		}

		contactRequestCacheModel.emailAddress = getEmailAddress();

		String emailAddress = contactRequestCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			contactRequestCacheModel.emailAddress = null;
		}

		contactRequestCacheModel.contactDetails = getContactDetails();

		String contactDetails = contactRequestCacheModel.contactDetails;

		if ((contactDetails != null) && (contactDetails.length() == 0)) {
			contactRequestCacheModel.contactDetails = null;
		}

		contactRequestCacheModel.status = getStatus();

		String status = contactRequestCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			contactRequestCacheModel.status = null;
		}

		return contactRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContactRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContactRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ContactRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContactRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ContactRequest.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private long _contactRequestId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _emailAddress;
	private String _contactDetails;
	private String _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ContactRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ContactRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("contactRequestId", _contactRequestId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("emailAddress", _emailAddress);
		_columnOriginalValues.put("contactDetails", _contactDetails);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("contactRequestId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("firstName", 512L);

		columnBitmasks.put("lastName", 1024L);

		columnBitmasks.put("emailAddress", 2048L);

		columnBitmasks.put("contactDetails", 4096L);

		columnBitmasks.put("status", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ContactRequest _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1223571491