/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.nexcent.contact.model.impl;

import com.nexcent.contact.model.ContactRequest;
import com.nexcent.contact.service.ContactRequestLocalServiceUtil;

/**
 * The extended model base implementation for the ContactRequest service. Represents a row in the &quot;NXC_ContactRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactRequestImpl
 * @see ContactRequest
 * @generated
 */
public abstract class ContactRequestBaseImpl
	extends ContactRequestModelImpl implements ContactRequest {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact request model instance should use the <code>ContactRequest</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContactRequestLocalServiceUtil.addContactRequest(this);
		}
		else {
			ContactRequestLocalServiceUtil.updateContactRequest(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1575399774