#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/nexcent-contact
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Nexcent.Contact)
osgi.jaxrs.resource=true